// flow-typed signature: 6c4190f0446c296d2d95f1acdc7b9bcb
// flow-typed version: <<STUB>>/dom-tools_v^0.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-tools/dist/dom-tools' {
  declare module.exports: any;
}

declare module 'dom-tools/dist/dom-tools.min' {
  declare module.exports: any;
}

declare module 'dom-tools/src/addClass' {
  declare module.exports: any;
}

declare module 'dom-tools/src/addEventListener' {
  declare module.exports: any;
}

declare module 'dom-tools/src/after' {
  declare module.exports: any;
}

declare module 'dom-tools/src/append' {
  declare module.exports: any;
}

declare module 'dom-tools/src/before' {
  declare module.exports: any;
}

declare module 'dom-tools/src/canUseDOM' {
  declare module.exports: any;
}

declare module 'dom-tools/src/children' {
  declare module.exports: any;
}

declare module 'dom-tools/src/clone' {
  declare module.exports: any;
}

declare module 'dom-tools/src/contains' {
  declare module.exports: any;
}

declare module 'dom-tools/src/css' {
  declare module.exports: any;
}

declare module 'dom-tools/src/empty' {
  declare module.exports: any;
}

declare module 'dom-tools/src/find' {
  declare module.exports: any;
}

declare module 'dom-tools/src/getComputedStyle' {
  declare module.exports: any;
}

declare module 'dom-tools/src/hasClass' {
  declare module.exports: any;
}

declare module 'dom-tools/src/height' {
  declare module.exports: any;
}

declare module 'dom-tools/src/hide' {
  declare module.exports: any;
}

declare module 'dom-tools/src/html' {
  declare module.exports: any;
}

declare module 'dom-tools/src/index' {
  declare module.exports: any;
}

declare module 'dom-tools/src/insertAfter' {
  declare module.exports: any;
}

declare module 'dom-tools/src/nodeName' {
  declare module.exports: any;
}

declare module 'dom-tools/src/offset' {
  declare module.exports: any;
}

declare module 'dom-tools/src/outerHeight' {
  declare module.exports: any;
}

declare module 'dom-tools/src/outerWidth' {
  declare module.exports: any;
}

declare module 'dom-tools/src/parent' {
  declare module.exports: any;
}

declare module 'dom-tools/src/prepend' {
  declare module.exports: any;
}

declare module 'dom-tools/src/remove' {
  declare module.exports: any;
}

declare module 'dom-tools/src/removeClass' {
  declare module.exports: any;
}

declare module 'dom-tools/src/removeEventListener' {
  declare module.exports: any;
}

declare module 'dom-tools/src/show' {
  declare module.exports: any;
}

declare module 'dom-tools/src/utils/camelize' {
  declare module.exports: any;
}

declare module 'dom-tools/src/utils/camelizeStyle' {
  declare module.exports: any;
}

declare module 'dom-tools/src/utils/getWindow' {
  declare module.exports: any;
}

declare module 'dom-tools/src/utils/ownerDocument' {
  declare module.exports: any;
}

declare module 'dom-tools/src/width' {
  declare module.exports: any;
}

declare module 'dom-tools/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-tools/dist/dom-tools.js' {
  declare module.exports: $Exports<'dom-tools/dist/dom-tools'>;
}
declare module 'dom-tools/dist/dom-tools.min.js' {
  declare module.exports: $Exports<'dom-tools/dist/dom-tools.min'>;
}
declare module 'dom-tools/src/addClass.js' {
  declare module.exports: $Exports<'dom-tools/src/addClass'>;
}
declare module 'dom-tools/src/addEventListener.js' {
  declare module.exports: $Exports<'dom-tools/src/addEventListener'>;
}
declare module 'dom-tools/src/after.js' {
  declare module.exports: $Exports<'dom-tools/src/after'>;
}
declare module 'dom-tools/src/append.js' {
  declare module.exports: $Exports<'dom-tools/src/append'>;
}
declare module 'dom-tools/src/before.js' {
  declare module.exports: $Exports<'dom-tools/src/before'>;
}
declare module 'dom-tools/src/canUseDOM.js' {
  declare module.exports: $Exports<'dom-tools/src/canUseDOM'>;
}
declare module 'dom-tools/src/children.js' {
  declare module.exports: $Exports<'dom-tools/src/children'>;
}
declare module 'dom-tools/src/clone.js' {
  declare module.exports: $Exports<'dom-tools/src/clone'>;
}
declare module 'dom-tools/src/contains.js' {
  declare module.exports: $Exports<'dom-tools/src/contains'>;
}
declare module 'dom-tools/src/css.js' {
  declare module.exports: $Exports<'dom-tools/src/css'>;
}
declare module 'dom-tools/src/empty.js' {
  declare module.exports: $Exports<'dom-tools/src/empty'>;
}
declare module 'dom-tools/src/find.js' {
  declare module.exports: $Exports<'dom-tools/src/find'>;
}
declare module 'dom-tools/src/getComputedStyle.js' {
  declare module.exports: $Exports<'dom-tools/src/getComputedStyle'>;
}
declare module 'dom-tools/src/hasClass.js' {
  declare module.exports: $Exports<'dom-tools/src/hasClass'>;
}
declare module 'dom-tools/src/height.js' {
  declare module.exports: $Exports<'dom-tools/src/height'>;
}
declare module 'dom-tools/src/hide.js' {
  declare module.exports: $Exports<'dom-tools/src/hide'>;
}
declare module 'dom-tools/src/html.js' {
  declare module.exports: $Exports<'dom-tools/src/html'>;
}
declare module 'dom-tools/src/index.js' {
  declare module.exports: $Exports<'dom-tools/src/index'>;
}
declare module 'dom-tools/src/insertAfter.js' {
  declare module.exports: $Exports<'dom-tools/src/insertAfter'>;
}
declare module 'dom-tools/src/nodeName.js' {
  declare module.exports: $Exports<'dom-tools/src/nodeName'>;
}
declare module 'dom-tools/src/offset.js' {
  declare module.exports: $Exports<'dom-tools/src/offset'>;
}
declare module 'dom-tools/src/outerHeight.js' {
  declare module.exports: $Exports<'dom-tools/src/outerHeight'>;
}
declare module 'dom-tools/src/outerWidth.js' {
  declare module.exports: $Exports<'dom-tools/src/outerWidth'>;
}
declare module 'dom-tools/src/parent.js' {
  declare module.exports: $Exports<'dom-tools/src/parent'>;
}
declare module 'dom-tools/src/prepend.js' {
  declare module.exports: $Exports<'dom-tools/src/prepend'>;
}
declare module 'dom-tools/src/remove.js' {
  declare module.exports: $Exports<'dom-tools/src/remove'>;
}
declare module 'dom-tools/src/removeClass.js' {
  declare module.exports: $Exports<'dom-tools/src/removeClass'>;
}
declare module 'dom-tools/src/removeEventListener.js' {
  declare module.exports: $Exports<'dom-tools/src/removeEventListener'>;
}
declare module 'dom-tools/src/show.js' {
  declare module.exports: $Exports<'dom-tools/src/show'>;
}
declare module 'dom-tools/src/utils/camelize.js' {
  declare module.exports: $Exports<'dom-tools/src/utils/camelize'>;
}
declare module 'dom-tools/src/utils/camelizeStyle.js' {
  declare module.exports: $Exports<'dom-tools/src/utils/camelizeStyle'>;
}
declare module 'dom-tools/src/utils/getWindow.js' {
  declare module.exports: $Exports<'dom-tools/src/utils/getWindow'>;
}
declare module 'dom-tools/src/utils/ownerDocument.js' {
  declare module.exports: $Exports<'dom-tools/src/utils/ownerDocument'>;
}
declare module 'dom-tools/src/width.js' {
  declare module.exports: $Exports<'dom-tools/src/width'>;
}
declare module 'dom-tools/webpack.config.js' {
  declare module.exports: $Exports<'dom-tools/webpack.config'>;
}
