// flow-typed signature: 9419911055a93aea4e844e33801ac29b
// flow-typed version: <<STUB>>/electron-meteor_v^0.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-meteor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-meteor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-meteor/dist/Call' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/Collection' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/CollectionFS/FSCollection' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/CollectionFS/FSCollectionImagesPreloader' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/CollectionFS/setProperties' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/components/ComplexListView' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/components/createContainer' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/components/ListView' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/components/Mixin' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/Data' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/lib/ddp' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/lib/queue' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/lib/Random' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/lib/socket' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/Meteor' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/Call' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/Collection' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/CollectionFS/FSCollection' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/CollectionFS/FSCollectionImagesPreloader' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/CollectionFS/setProperties' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/components/createContainer' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/components/Mixin' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/Data' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/Meteor' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/user/Accounts' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/src/user/User' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/user/Accounts' {
  declare module.exports: any;
}

declare module 'electron-meteor/dist/user/User' {
  declare module.exports: any;
}

declare module 'electron-meteor/lib/ddp' {
  declare module.exports: any;
}

declare module 'electron-meteor/lib/queue' {
  declare module.exports: any;
}

declare module 'electron-meteor/lib/Random' {
  declare module.exports: any;
}

declare module 'electron-meteor/lib/socket' {
  declare module.exports: any;
}

declare module 'electron-meteor/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/Call' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/Collection' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/CollectionFS/FSCollection' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/CollectionFS/FSCollectionImagesPreloader' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/CollectionFS/setProperties' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/components/createContainer' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/components/Mixin' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/Data' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/Meteor' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/user/Accounts' {
  declare module.exports: any;
}

declare module 'electron-meteor/src/user/User' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-meteor/dist/Call.js' {
  declare module.exports: $Exports<'electron-meteor/dist/Call'>;
}
declare module 'electron-meteor/dist/Collection.js' {
  declare module.exports: $Exports<'electron-meteor/dist/Collection'>;
}
declare module 'electron-meteor/dist/CollectionFS/FSCollection.js' {
  declare module.exports: $Exports<'electron-meteor/dist/CollectionFS/FSCollection'>;
}
declare module 'electron-meteor/dist/CollectionFS/FSCollectionImagesPreloader.js' {
  declare module.exports: $Exports<'electron-meteor/dist/CollectionFS/FSCollectionImagesPreloader'>;
}
declare module 'electron-meteor/dist/CollectionFS/setProperties.js' {
  declare module.exports: $Exports<'electron-meteor/dist/CollectionFS/setProperties'>;
}
declare module 'electron-meteor/dist/components/ComplexListView.js' {
  declare module.exports: $Exports<'electron-meteor/dist/components/ComplexListView'>;
}
declare module 'electron-meteor/dist/components/createContainer.js' {
  declare module.exports: $Exports<'electron-meteor/dist/components/createContainer'>;
}
declare module 'electron-meteor/dist/components/ListView.js' {
  declare module.exports: $Exports<'electron-meteor/dist/components/ListView'>;
}
declare module 'electron-meteor/dist/components/Mixin.js' {
  declare module.exports: $Exports<'electron-meteor/dist/components/Mixin'>;
}
declare module 'electron-meteor/dist/Data.js' {
  declare module.exports: $Exports<'electron-meteor/dist/Data'>;
}
declare module 'electron-meteor/dist/lib/ddp.js' {
  declare module.exports: $Exports<'electron-meteor/dist/lib/ddp'>;
}
declare module 'electron-meteor/dist/lib/queue.js' {
  declare module.exports: $Exports<'electron-meteor/dist/lib/queue'>;
}
declare module 'electron-meteor/dist/lib/Random.js' {
  declare module.exports: $Exports<'electron-meteor/dist/lib/Random'>;
}
declare module 'electron-meteor/dist/lib/socket.js' {
  declare module.exports: $Exports<'electron-meteor/dist/lib/socket'>;
}
declare module 'electron-meteor/dist/lib/utils.js' {
  declare module.exports: $Exports<'electron-meteor/dist/lib/utils'>;
}
declare module 'electron-meteor/dist/Meteor.js' {
  declare module.exports: $Exports<'electron-meteor/dist/Meteor'>;
}
declare module 'electron-meteor/dist/src/Call.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/Call'>;
}
declare module 'electron-meteor/dist/src/Collection.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/Collection'>;
}
declare module 'electron-meteor/dist/src/CollectionFS/FSCollection.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/CollectionFS/FSCollection'>;
}
declare module 'electron-meteor/dist/src/CollectionFS/FSCollectionImagesPreloader.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/CollectionFS/FSCollectionImagesPreloader'>;
}
declare module 'electron-meteor/dist/src/CollectionFS/setProperties.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/CollectionFS/setProperties'>;
}
declare module 'electron-meteor/dist/src/components/createContainer.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/components/createContainer'>;
}
declare module 'electron-meteor/dist/src/components/Mixin.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/components/Mixin'>;
}
declare module 'electron-meteor/dist/src/Data.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/Data'>;
}
declare module 'electron-meteor/dist/src/Meteor.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/Meteor'>;
}
declare module 'electron-meteor/dist/src/user/Accounts.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/user/Accounts'>;
}
declare module 'electron-meteor/dist/src/user/User.js' {
  declare module.exports: $Exports<'electron-meteor/dist/src/user/User'>;
}
declare module 'electron-meteor/dist/user/Accounts.js' {
  declare module.exports: $Exports<'electron-meteor/dist/user/Accounts'>;
}
declare module 'electron-meteor/dist/user/User.js' {
  declare module.exports: $Exports<'electron-meteor/dist/user/User'>;
}
declare module 'electron-meteor/lib/ddp.js' {
  declare module.exports: $Exports<'electron-meteor/lib/ddp'>;
}
declare module 'electron-meteor/lib/queue.js' {
  declare module.exports: $Exports<'electron-meteor/lib/queue'>;
}
declare module 'electron-meteor/lib/Random.js' {
  declare module.exports: $Exports<'electron-meteor/lib/Random'>;
}
declare module 'electron-meteor/lib/socket.js' {
  declare module.exports: $Exports<'electron-meteor/lib/socket'>;
}
declare module 'electron-meteor/lib/utils.js' {
  declare module.exports: $Exports<'electron-meteor/lib/utils'>;
}
declare module 'electron-meteor/src/Call.js' {
  declare module.exports: $Exports<'electron-meteor/src/Call'>;
}
declare module 'electron-meteor/src/Collection.js' {
  declare module.exports: $Exports<'electron-meteor/src/Collection'>;
}
declare module 'electron-meteor/src/CollectionFS/FSCollection.js' {
  declare module.exports: $Exports<'electron-meteor/src/CollectionFS/FSCollection'>;
}
declare module 'electron-meteor/src/CollectionFS/FSCollectionImagesPreloader.js' {
  declare module.exports: $Exports<'electron-meteor/src/CollectionFS/FSCollectionImagesPreloader'>;
}
declare module 'electron-meteor/src/CollectionFS/setProperties.js' {
  declare module.exports: $Exports<'electron-meteor/src/CollectionFS/setProperties'>;
}
declare module 'electron-meteor/src/components/createContainer.js' {
  declare module.exports: $Exports<'electron-meteor/src/components/createContainer'>;
}
declare module 'electron-meteor/src/components/Mixin.js' {
  declare module.exports: $Exports<'electron-meteor/src/components/Mixin'>;
}
declare module 'electron-meteor/src/Data.js' {
  declare module.exports: $Exports<'electron-meteor/src/Data'>;
}
declare module 'electron-meteor/src/Meteor.js' {
  declare module.exports: $Exports<'electron-meteor/src/Meteor'>;
}
declare module 'electron-meteor/src/user/Accounts.js' {
  declare module.exports: $Exports<'electron-meteor/src/user/Accounts'>;
}
declare module 'electron-meteor/src/user/User.js' {
  declare module.exports: $Exports<'electron-meteor/src/user/User'>;
}
