// flow-typed signature: 038494dc83bdb3b7f1f6fc589b663919
// flow-typed version: <<STUB>>/jquery-slimscroll_v^1.3.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-slimscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-slimscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-slimscroll/examples/libs/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jquery-slimscroll/jquery.slimscroll' {
  declare module.exports: any;
}

declare module 'jquery-slimscroll/jquery.slimscroll.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-slimscroll/examples/libs/prettify/prettify.js' {
  declare module.exports: $Exports<'jquery-slimscroll/examples/libs/prettify/prettify'>;
}
declare module 'jquery-slimscroll/jquery.slimscroll.js' {
  declare module.exports: $Exports<'jquery-slimscroll/jquery.slimscroll'>;
}
declare module 'jquery-slimscroll/jquery.slimscroll.min.js' {
  declare module.exports: $Exports<'jquery-slimscroll/jquery.slimscroll.min'>;
}
